FROM nvidia/cuda:12.8.1-cudnn-runtime-ubuntu24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO_NAME="jazzy"
ENV TZ=Europe/Berlin
ENV PIP_BREAK_SYSTEM_PACKAGES=1

SHELL ["/bin/bash", "-c"]

RUN apt update -y && apt upgrade -y
RUN apt install -y locales
RUN locale-gen en_US en_US.UTF-8
RUN update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

ENV LANG=en_US.UTF-8

RUN apt install -y software-properties-common
RUN add-apt-repository universe
RUN apt update && apt install curl -y
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
RUN apt update -y

RUN apt install -y python3-pip \
    tzdata \
    net-tools \
    iputils-ping \
    git \
    sudo \
    nano \
    wget \
    iproute2 \
    pkg-config

RUN apt install -y ros-${ROS_DISTRO}-desktop \
    ros-${ROS_DISTRO}-geographic-msgs \
    ros-${ROS_DISTRO}-tf-transformations \
    ros-${ROS_DISTRO}-rosbridge-suite 

RUN apt install -y nlohmann-json3-dev \
    python3-colcon-common-extensions \
    libunwind-dev libstdc++-12-dev \
    jq

RUN apt install -y libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    libgstreamer-plugins-bad1.0-dev \
    libgstreamer-plugins-good1.0-dev \
    gir1.2-gst-rtsp-server-1.0 \
    libgstrtspserver-1.0-dev \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav

RUN pip3 install pandas
RUN pip3 install alns
RUN pip3 install scikit-learn
RUN pip3 install google-genai
RUN pip3 install anthropic
RUN pip3 install openai
RUN pip3 install "transformers==4.46.3"
RUN pip3 install unified-planning[engines]
RUN pip3 install up-esb

RUN pip3 install ultralytics --ignore-installed sympy
RUN pip3 install webcolors
RUN pip3 install "scipy==1.15.1"
RUN pip3 install "numpy==1.26.4"
RUN pip3 install pyparsing

RUN pip3 install requests
RUN pip3 install oauthlib
RUN pip3 install requests-oauthlib
RUN pip3 install rasterio

RUN pip3 install kconfiglib
RUN pip3 install future
RUN pip3 install pyros-genmsg
RUN pip3 install --force-reinstall --ignore-installed "transforms3d==0.4.2"
RUN pip3 install geopy
RUN pip3 install jsonschema
RUN pip3 install valkey
RUN pip3 install shapely
RUN pip3 install "tornado==6.4.2" # needed for ros2 bridge
RUN pip3 install nltk
RUN pip3 install ortools
RUN pip3 install pyproj
# RUN pip3 install "tornado==4.5.3" # CONFLICT needed for airsim
# RUN pip3 install "msgpack-rpc-python==0.4.1"
# RUN pip3 install --no-build-isolation airsim
RUN pip3 install zmq
RUN pip3 install cplex docplex

COPY copy_files/ibm_cplex copy_files/ibm_cplex
ENV CPLEX_STUDIO_DIR2212=/copy_files/ibm_cplex
ENV CPLEX_STUDIO_BINARIES2212=/copy_files/ibm_cplex/cpoptimizer/bin/x86-64_linux
ENV PATH=/copy_files/ibm_cplex/cpoptimizer/bin/x86-64_linux:/copy_files/ibm_cplex/cplex/bin/x86-64_linux:${PATH}
# RUN docplex config --upgrade /copy_files/ibm_cplex

WORKDIR /root
RUN git clone https://github.com/PX4/PX4-Autopilot.git
WORKDIR /root/PX4-Autopilot
RUN git checkout -f v1.15.4
RUN git submodule update --init --recursive
RUN make px4_sitl_default

# Fix Planner for UP
COPY copy_files/up_planner/lpg_planner.py /tmp/lpg_planner.py
WORKDIR /root
RUN UP_LPG_DIR="$(python3 -c 'import sysconfig; print(sysconfig.get_paths()["platlib"] + "/up_lpg")')" && \
    chmod +x "$UP_LPG_DIR/lpg" && \
    ls -l "$UP_LPG_DIR/lpg" && \
    cp /tmp/lpg_planner.py "$UP_LPG_DIR/lpg_planner.py"

WORKDIR /root
RUN mkdir valkey
WORKDIR /root/valkey
RUN git clone https://github.com/valkey-io/valkey
WORKDIR /root/valkey/valkey
RUN make

WORKDIR /root/valkey
RUN git clone https://github.com/valkey-io/valkeyJSON
WORKDIR /root/valkey/valkeyJSON
RUN sed -i "s|"OVERRIDE_FIND_PACKAGE"|""|" ./tst/CMakeLists.txt
RUN mkdir build
WORKDIR /root/valkey/valkeyJSON/build
RUN cmake ..
RUN make

WORKDIR /root
RUN mkdir scripts
COPY copy_files/px4/sitl_multiple_run.sh /root/scripts
RUN chmod +x /root/scripts/sitl_multiple_run.sh

RUN pip3 install mavsdk
RUN pip3 install pymap3d

RUN echo 'source /opt/ros/${ROS_DISTRO}/setup.bash' >> /root/.bashrc
RUN echo 'source /root/AUSPEX/utils/auspex_aliases.sh' >> /root/.bashrc
RUN echo 'source /root/AUSPEX/utils/auspex_exports.sh' >> /root/.bashrc

WORKDIR /root
